name: Manual trigger

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
jobs:
  manual:
    name: Manual Jon
    runs-on: ubuntu-latest
    steps:
    - name: Run Manual Workflow Step
      run: |
        echo "Run Manual Workflow Step!"
