
name: test
on:
  workflow_dispatch:
  push:
jobs:
  a:
    name: Lane Check
    runs-on: ubuntu-latest
    steps:
      - run: echo "A"
      - id: set
        run: |
          echo "::set-output name=run_job_b::yes"
    outputs:
      run_job_b: ${{ steps.set.outputs.run_job_b }}
  b:
    name: Express Publish
    runs-on: ubuntu-latest
    needs:
      - a
    if: needs.a.outputs.run_job_b == 'yes'
    steps:
      - run: echo "B"
  d:
    name: Normal Publish
    runs-on: ubuntu-latest
    needs:
      - a
    if: needs.a.outputs.run_job_b == 'no'
    steps:
      - run: echo "B"
  c:
    name: SCM Tag
    runs-on: ubuntu-latest
    needs:
      - a
      - b
      - d
    if: |
      always() && needs.a.result == 'success' && ((needs.b.result == 'success' || needs.b.result == 'skipped') || (needs.d.result == 'success' || needs.d.result == 'skipped'))
    steps:
      - run: echo "C"